version: "3.8"
services:
  meilisearch:
    image: getmeili/meilisearch:v0.25.2
    command: ./meilisearch --master-key=key --no-analytics=true
    ports:
      - target: 7700
        published: 7700
        protocol: tcp
    volumes:
      - ./data.ms:/data.ms

volumes:
  postgres:
  pgadmin: