[database]
jdbcURL = "jdbc:sqlite:db/dinf.db"

[urls]

[urls.share]
salt = "salt"
length = 6

[server]
port = 8080
baseURL = "http://localhost:8080"

[htmx]
timeout = "5s"

[toggles]
showUserButtons = false

[login]

[login.password]
enabled = false

[login.oauth]
[login.oauth.google]
enabled = false
clientId = ""
clientSecret = ""
