[database]
jdbcURL = "jdbc:sqlite:db/dinf.db"

[urls]

[urls.share]
salt = "salt"
length = 6

[server]
port = 8080
baseURL = "http://localhost:8080"

[search]
url = "http://localhost:7700"
key = "key"

[htmx]
timeout = "5s"

[toggles]
passwordEnabled = false
showUserButtons = false