name: CI

on:
  push:
    paths-ignore:
      - '*.md'

jobs:
  build:
    uses: ustits/dinf/.github/workflows/build_workflow.yml@main
  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    uses: ustits/dinf/.github/workflows/deploy_workflow.yml@main
    with:
      version: ${{ github.run_id }}
    secrets:
      host: ${{ secrets.HOST }}
      username: ${{ secrets.USERNAME }}
      ssh_port: ${{ secrets.PORT }}
      ssh_key: ${{ secrets.KEY }}
