name: CD

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Load distribution
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success

      - name: Display structure of downloaded files
        run: ls -R

      - name: Transfer files to server
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "distribution/backend.tar"
          target: "dinf_v$GITHUB_RUN_ID"

      - name: Prepare
        uses: garygrossgarten/github-action-ssh@v0.6.3
        with:
          command: tar xf dinf_v$GITHUB_RUN_ID/distribution/backend.tar
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.KEY }}
